### ISSUE TITLE
unzip-epub

### ISSUE THREAD

**Issue by manuel-uberti** [wasamasa/teapub#1]
Hi,

first of all thanks for this repo, I'm always interested in studying CHICKEN Scheme projects. I followed your instructions and when I try the command `csc teapub.scm`, I get this:

```
Warning: in local unknown procedure,
  in local unknown procedure,
  in local unknown procedure,
  in toplevel procedure `unzip-epub':
  (teapub.scm:40) in procedure call to `port->fileno', expected argument #1 of type `(or input-port output-port)', but was given an argument of type `fixnum'
```

Is this expected? Can I use teapub anyway?

FWIW, unzip is available:

```
~/githubs/teapub % which unzip
/usr/bin/unzip
```

**Comment by manuel-uberti** [comment]
Ok, forget this issue: I can view epubs despite that warning. :)

**Comment by wasamasa** [comment]
I'm still curious what exactly is happening there.  Could you provide more details about your system and the version of `chicken`?

**Comment by manuel-uberti** [comment]
Sure thing:
- OS: Debian Jessie
- `chicken` version

```
~ % chicken -version
(c) 2008-2014, The Chicken Team
(c) 2000-2007, Felix L. Winkelmann
Version 4.9.0.1 (stability/4.9.0) (rev 8b3189b)
linux-unix-gnu-x86-64 [ 64bit manyargs dload ptables ]
bootstrapped 2014-06-07
```
- `unzip` version

```
unzip:
  Installed: 6.0-16+deb8u2
  Candidate: 6.0-16+deb8u2
  Version table:
 *** 6.0-16+deb8u2 0
        500 http://ftp.de.debian.org/debian/ jessie/main amd64 Packages
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
        100 /var/lib/dpkg/status
```
- `webkitgtk` version

```
libwebkitgtk-3.0-dev:
  Installed: 2.4.9-1~deb8u1
  Candidate: 2.4.9-1~deb8u1
  Version table:
 *** 2.4.9-1~deb8u1 0
        500 http://ftp.de.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by wasamasa** [comment]
Great, I can reproduce it with 4.9.0.1 as well.

**Comment by wasamasa** [comment]
From what I can tell, this warning originates from me using special syntax in the `unzip-epub` procedure to redirect stderr to stdout (then redirecting that to `/dev/null`).  Replacing it with a wordier redirection makes the warning go away.

Looking deeper this appears to happen because the `types.db` file in 4.9.0.1 is different from my current release.  Compare

``` scm
(port? (#(procedure #:pure #:predicate (or input-port output-port)) port? (*) boolean))
```

to

``` scm
(port? (#(procedure #:pure) port? (*) boolean))
```

I don't quite understand the syntax for these, so I'll ask elsewhere.

As the warning appears to be erroneous and the workaround is rather silly, I will probably not "fix" this.

**Comment by manuel-uberti** [comment]
Great. Yes, do not worry about the warning if it causes you troubles. Teapub is working just fine. :)
